-- ERP sales integration (Phase 4, Option A — see docs/erp-sales-integration-design.md):
-- a coupon sale received from Business Central, resolved to CMS-assigned serials.

CREATE TABLE coupon_sales (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bc_document_number varchar(50)  NOT NULL UNIQUE,
    location_id        bigint       NOT NULL REFERENCES locations (id),
    fuel_type_id       bigint       NOT NULL REFERENCES fuel_types (id),
    denomination       numeric(10,2) NOT NULL,
    requested_count    integer      NOT NULL,
    status             varchar(20)  NOT NULL,
    customer_reference varchar(100),
    failure_reason     varchar(255),
    received_at        timestamp(6) NOT NULL,
    assigned_at        timestamp(6),
    pushed_at          timestamp(6)
);

CREATE INDEX idx_coupon_sale_status ON coupon_sales (status);

CREATE TABLE coupon_sale_coupon_numbers (
    coupon_sale_id bigint      NOT NULL REFERENCES coupon_sales (id),
    coupon_number  varchar(20) NOT NULL
);

CREATE INDEX idx_coupon_sale_coupon_numbers_sale ON coupon_sale_coupon_numbers (coupon_sale_id);