-- Baseline of the schema previously managed by Hibernate ddl-auto: update.
-- On the pre-existing database Flyway baselines at version 1 and SKIPS this script;
-- it only runs on a fresh, empty database.

CREATE TABLE fuel_types (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(20)  NOT NULL UNIQUE,
    type_code   varchar(5)   NOT NULL UNIQUE,
    description varchar(100),
    active      boolean      NOT NULL
);

CREATE TABLE coupons (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_number varchar(20)  NOT NULL UNIQUE,
    fuel_type_id  bigint       NOT NULL REFERENCES fuel_types (id),
    status        varchar(10)  NOT NULL,
    created_at    timestamp(6) NOT NULL
);

CREATE INDEX idx_coupon_fuel_type_id ON coupons (fuel_type_id);
CREATE INDEX idx_coupon_status ON coupons (status);
CREATE INDEX idx_coupon_created_at ON coupons (created_at);

CREATE TABLE coupon_sequences (
    fuel_type_id   bigint PRIMARY KEY REFERENCES fuel_types (id),
    current_letter char(1) DEFAULT 'M' NOT NULL,
    issued_count   bigint  DEFAULT 0   NOT NULL
);

CREATE TABLE bulk_generation_config (
    id            bigint PRIMARY KEY,
    max_count     integer NOT NULL,
    max_page_size integer DEFAULT 500 NOT NULL,
    updated_at    timestamp(6)
);