-- Multi-line sale events (§11.6 of docs/erp-sales-integration-design.md). A BC sales document
-- can carry more than one fuel type + denomination, so the line-level columns move off
-- coupon_sales into a child table; coupon_sales.status becomes the rollup of the line
-- statuses. coupon_sales holds no data yet (mock/tests only), so no row migration is needed.
--
-- Written idempotently (IF EXISTS / IF NOT EXISTS) so it converges to the target schema
-- whether the DB is pristine or had the shape hand-applied during the checksum incident.

DROP TABLE IF EXISTS coupon_sale_coupon_numbers;

ALTER TABLE coupon_sales DROP COLUMN IF EXISTS fuel_type_id;
ALTER TABLE coupon_sales DROP COLUMN IF EXISTS denomination;
ALTER TABLE coupon_sales DROP COLUMN IF EXISTS requested_count;
ALTER TABLE coupon_sales DROP COLUMN IF EXISTS failure_reason;

-- coupon_sales now: id, bc_document_number, location_id, status (rollup — ASSIGNED /
-- PARTIALLY_ASSIGNED / FAILED / PUSHED), customer_reference, received_at, assigned_at,
-- pushed_at. idx_coupon_sale_status (from V16) still applies.

CREATE TABLE IF NOT EXISTS coupon_sale_lines (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_sale_id  bigint        NOT NULL REFERENCES coupon_sales (id),
    line_number     integer       NOT NULL,
    fuel_type_id    bigint        NOT NULL REFERENCES fuel_types (id),
    denomination    numeric(10,2) NOT NULL,
    requested_count integer       NOT NULL,
    -- BC's signal that this line is sold as whole intact books, not a loose count. Stored
    -- now; the whole-book allocation path itself is a later build item (§11.4).
    whole_books     boolean       NOT NULL DEFAULT false,
    -- ASSIGNED or FAILED — one line's own outcome.
    status          varchar(20)   NOT NULL,
    failure_reason  varchar(255),
    CONSTRAINT uq_coupon_sale_line UNIQUE (coupon_sale_id, line_number)
);

CREATE INDEX IF NOT EXISTS idx_coupon_sale_lines_sale ON coupon_sale_lines (coupon_sale_id);

-- Serials assigned against one line, in the order they were drawn. Empty for a FAILED line.
CREATE TABLE IF NOT EXISTS coupon_sale_line_coupon_numbers (
    coupon_sale_line_id bigint      NOT NULL REFERENCES coupon_sale_lines (id),
    coupon_number       varchar(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_coupon_sale_line_coupon_numbers_line
    ON coupon_sale_line_coupon_numbers (coupon_sale_line_id);
