-- Security audit trail (Phase 3): every request that was denied (401/403) or that mutated data
-- and was allowed. Read-only GETs that succeed are deliberately not logged here — high volume,
-- low audit value — see SecurityAuditInterceptor for the exact rule.
CREATE TABLE security_audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Null for UNAUTHENTICATED: no valid token means no principal to name.
    principal   varchar(100),
    roles       varchar(255),
    http_method varchar(10)  NOT NULL,
    path        varchar(255) NOT NULL,
    status_code integer      NOT NULL,
    outcome     varchar(20)  NOT NULL,
    reason      varchar(255),
    created_at  timestamp(6) NOT NULL
);

CREATE INDEX idx_security_audit_created_at ON security_audit_log (created_at);
CREATE INDEX idx_security_audit_outcome ON security_audit_log (outcome) WHERE outcome <> 'ALLOWED';
