-- Local shadow of Keycloak-managed attendant accounts: written durably BEFORE the Keycloak admin
-- call is attempted, so a registration survives a Keycloak outage instead of being lost. A
-- PENDING/FAILED row IS the retry queue for AttendantSyncSweep — nothing extra is persisted, same
-- pattern as ERP posting (coupon_approval_requests PENDING rows).
CREATE TABLE app_users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id     varchar(36),
    username        varchar(50)  NOT NULL,
    email           varchar(100) NOT NULL,
    first_name      varchar(50)  NOT NULL,
    last_name       varchar(50)  NOT NULL,
    role            varchar(20)  NOT NULL DEFAULT 'ATTENDANT',
    location_code   varchar(10),
    sync_status     varchar(20)  NOT NULL,
    sync_attempts   integer      NOT NULL DEFAULT 0,
    last_sync_error varchar(500),
    created_at      timestamp(6) NOT NULL,
    updated_at      timestamp(6)
);

CREATE UNIQUE INDEX uq_app_users_username ON app_users (lower(username));
CREATE UNIQUE INDEX uq_app_users_keycloak_id ON app_users (keycloak_id) WHERE keycloak_id IS NOT NULL;
CREATE INDEX idx_app_users_sync_status ON app_users (sync_status) WHERE sync_status <> 'SYNCED';
