-- Virtual coupons sold through a partner bank: the bank collects payment and settles with
-- Petrotrade offline; the CMS mints DIGITAL coupons on demand and records the purchase here
-- for reconciliation.

-- Price per litre the bank must charge. NULL = not on sale through the bank channel.
ALTER TABLE fuel_types ADD COLUMN price_per_litre numeric(10,2);

CREATE TABLE bank_purchases (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_reference     varchar(50)   NOT NULL UNIQUE,
    customer_reference varchar(100),
    fuel_type_id       bigint        NOT NULL REFERENCES fuel_types (id),
    batch_id           bigint        NOT NULL REFERENCES coupon_batches (id),
    litres             numeric(12,2) NOT NULL,
    -- Snapshot of the price at purchase time, so reconciliation survives later price changes.
    price_per_litre    numeric(10,2) NOT NULL,
    amount             numeric(12,2) NOT NULL,
    status             varchar(20)   NOT NULL,
    reversal_reason    varchar(255),
    created_at         timestamp(6)  NOT NULL,
    reversed_at        timestamp(6)
);
