-- Phase 1: coupon lifecycle + inventory.
-- Widens the status model, remaps legacy values, and introduces locations,
-- batches and the immutable movement audit log.

-- Hibernate's ddl-auto:update previously generated this CHECK constraint, baking in the
-- old 3-value enum. It must go before the status column is widened or remapped, otherwise
-- both operations below are rejected by the constraint. The lifecycle state machine
-- (application-level, see CouponStateMachine) is now the sole source of truth for valid
-- statuses, so it is intentionally not replaced with an equivalent DB-level check.
ALTER TABLE coupons DROP CONSTRAINT IF EXISTS coupons_status_check;

ALTER TABLE coupons ALTER COLUMN status TYPE varchar(20);

UPDATE coupons SET status = 'IN_STOCK' WHERE status = 'ACTIVE';
UPDATE coupons SET status = 'REDEEMED' WHERE status = 'USED';

CREATE TABLE locations (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       varchar(10)  NOT NULL UNIQUE,
    name       varchar(100) NOT NULL UNIQUE,
    type       varchar(20)  NOT NULL,
    address    varchar(255),
    active     boolean      NOT NULL DEFAULT true,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);

-- Default location; the coupon backfill below depends on it, so it is seeded here
-- rather than in DataInitializer.
INSERT INTO locations (code, name, type, active, created_at)
VALUES ('HQ', 'Head Office', 'HQ', true, now());

CREATE TABLE coupon_batches (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number       varchar(30)  NOT NULL UNIQUE,
    fuel_type_id       bigint       NOT NULL REFERENCES fuel_types (id),
    coupon_type        varchar(10)  NOT NULL,
    quantity           integer      NOT NULL,
    origin_location_id bigint       NOT NULL REFERENCES locations (id),
    expiry_date        date,
    created_by         varchar(100),
    created_at         timestamp(6) NOT NULL
);

CREATE INDEX idx_batch_fuel_type_id ON coupon_batches (fuel_type_id);
CREATE INDEX idx_batch_origin_location_id ON coupon_batches (origin_location_id);
CREATE INDEX idx_batch_created_at ON coupon_batches (created_at);

CREATE TABLE coupon_movements (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id        bigint       NOT NULL REFERENCES coupons (id),
    movement_type    varchar(20)  NOT NULL,
    from_status      varchar(20),
    to_status        varchar(20)  NOT NULL,
    from_location_id bigint REFERENCES locations (id),
    to_location_id   bigint REFERENCES locations (id),
    performed_by     varchar(100),
    reason           varchar(255),
    reference_type   varchar(30),
    reference_id     bigint,
    created_at       timestamp(6) NOT NULL
);

CREATE INDEX idx_movement_coupon_created ON coupon_movements (coupon_id, created_at);

ALTER TABLE coupons
    ADD COLUMN batch_id            bigint,
    ADD COLUMN current_location_id bigint,
    ADD COLUMN coupon_type         varchar(10) NOT NULL DEFAULT 'PHYSICAL',
    ADD COLUMN expiry_date         date,
    ADD COLUMN updated_at          timestamp(6);

-- Legacy coupons are attributed to HQ; their movement history starts at go-live.
UPDATE coupons SET current_location_id = (SELECT id FROM locations WHERE code = 'HQ');

ALTER TABLE coupons ALTER COLUMN current_location_id SET NOT NULL;

ALTER TABLE coupons
    ADD CONSTRAINT fk_coupon_batch FOREIGN KEY (batch_id) REFERENCES coupon_batches (id),
    ADD CONSTRAINT fk_coupon_current_location FOREIGN KEY (current_location_id) REFERENCES locations (id);

CREATE INDEX idx_coupon_batch_id ON coupons (batch_id);
CREATE INDEX idx_coupon_current_location_id ON coupons (current_location_id);
CREATE INDEX idx_coupon_location_status ON coupons (current_location_id, status);