-- Departments (organizational units, e.g. Stocks/Commercial/Retail) and a per-batch
-- position number on coupons, enabling range-based batch selection for transfers.

CREATE TABLE departments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       varchar(10)  NOT NULL UNIQUE,
    name       varchar(100) NOT NULL UNIQUE,
    active     boolean      NOT NULL DEFAULT true,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);

-- Default department; the coupon backfill below depends on it, so it is seeded here
-- rather than in DataInitializer (same reasoning as the HQ location seed in V2).
INSERT INTO departments (code, name, active, created_at)
VALUES ('STOCKS', 'Stocks', true, now());

ALTER TABLE coupons
    ADD COLUMN current_department_id bigint,
    ADD COLUMN batch_sequence        integer;

-- Legacy coupons are attributed to Stocks. batch_sequence is left null for them —
-- there is no meaningful position to assign retroactively (same precedent as batch_id
-- being left null for legacy rows in V2).
UPDATE coupons SET current_department_id = (SELECT id FROM departments WHERE code = 'STOCKS');

ALTER TABLE coupons ALTER COLUMN current_department_id SET NOT NULL;

ALTER TABLE coupons
    ADD CONSTRAINT fk_coupon_current_department FOREIGN KEY (current_department_id) REFERENCES departments (id);

CREATE INDEX idx_coupon_current_department_id ON coupons (current_department_id);
CREATE INDEX idx_coupon_batch_sequence ON coupons (batch_id, batch_sequence);

ALTER TABLE coupon_movements
    ADD COLUMN from_department_id bigint REFERENCES departments (id),
    ADD COLUMN to_department_id   bigint REFERENCES departments (id);
