-- Supervisor approval workflow: any transition/transfer that changes a coupon's location
-- and/or department is deferred into a PENDING request instead of applying immediately.

CREATE TABLE coupon_approval_requests (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type     varchar(20)  NOT NULL,
    batch_id         bigint REFERENCES coupon_batches (id),
    range_start      integer,
    range_end        integer,
    target_status    varchar(20),
    to_location_id   bigint REFERENCES locations (id),
    to_department_id bigint REFERENCES departments (id),
    reason           varchar(255),
    requested_by     varchar(100),
    requested_at     timestamp(6) NOT NULL,
    status           varchar(20)  NOT NULL,
    decided_by       varchar(100),
    decided_at       timestamp(6),
    decision_reason  varchar(255)
);

CREATE INDEX idx_approval_status ON coupon_approval_requests (status);
CREATE INDEX idx_approval_requested_at ON coupon_approval_requests (requested_at);

-- Explicit coupon numbers for TRANSITION-origin requests (empty for TRANSFER-origin ones).
CREATE TABLE coupon_approval_request_coupon_numbers (
    approval_request_id bigint      NOT NULL REFERENCES coupon_approval_requests (id),
    coupon_number        varchar(20) NOT NULL
);

CREATE INDEX idx_approval_request_coupon_numbers ON coupon_approval_request_coupon_numbers (approval_request_id);
