-- Receipt confirmation: a department-changing transfer no longer counts as complete once
-- the supervisor approves it (status APPROVED -> IN_TRANSIT). The receiving department must
-- separately confirm receipt (status IN_TRANSIT -> RECEIVED) before the coupons actually move
-- into their custody, mirroring the paper GRV/GIV process.

ALTER TABLE coupon_approval_requests
    ADD COLUMN received_by   varchar(100),
    ADD COLUMN received_at   timestamp(6),
    ADD COLUMN requisition_id bigint;

-- Requisitions: a department's request to Stock for coupons, in litres per denomination
-- (the digital Internal Purchase Requisition). Fulfilled over one or more approval requests,
-- since Stock may only be able to deliver part of what was asked for at a time (drawdown).

CREATE TABLE coupon_requisitions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id   bigint       NOT NULL REFERENCES departments (id),
    location_id     bigint       NOT NULL REFERENCES locations (id),
    requested_by    varchar(100),
    requested_at    timestamp(6) NOT NULL,
    status          varchar(20)  NOT NULL,
    decided_by      varchar(100),
    decided_at      timestamp(6),
    decision_reason varchar(255)
);

CREATE INDEX idx_requisition_status ON coupon_requisitions (status);
CREATE INDEX idx_requisition_requested_at ON coupon_requisitions (requested_at);

CREATE TABLE requisition_lines (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id   bigint         NOT NULL REFERENCES coupon_requisitions (id),
    denomination     numeric(10,2)  NOT NULL,
    requested_litres numeric(12,2)  NOT NULL,
    fulfilled_litres numeric(12,2)  NOT NULL DEFAULT 0
);

CREATE INDEX idx_requisition_line_requisition_id ON requisition_lines (requisition_id);

ALTER TABLE coupon_approval_requests
    ADD CONSTRAINT fk_approval_requisition FOREIGN KEY (requisition_id) REFERENCES coupon_requisitions (id);